sudo: required
services:
  - docker
  
before_install:
  - docker build -t kos672/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true kos672/react-test npm test
  
after_success:
  - docker build -t kos672/multi-client ./client
  - docker build -t kos672/multi-nginx ./nginx
  - docker build -t kos672/multi-server ./server
  - docker build -t kos672/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take given images and push to docker hub
  - docker push kos672/multi-client
  - docker push kos672/multi-nginx
  - docker push kos672/multi-server
  - docker push kos672/multi-worker